JF_WS_DIR = '/jf-data/workspaces'
JF_WS_HOST_DIR = '/jfbcore/{JF_WS_DIR}'.format(JF_WS_DIR=JF_WS_DIR)
JF_ETC_DIR = '/jf-data/etc_host'
JF_ETC_DIR_HOST_PATH = '/jfbcore/{JF_ETC_DIR}'.format(JF_ETC_DIR=JF_ETC_DIR) # /jfbcore/jf-data/etc_host
JF_ETC_DIR_POD_PATH = '/etc_host'
JF_UPLOAD_DIR = '/jf-data/tmp'
JF_LOG_DIR = '/jf-data/log'
JF_DB_DIR = '/jf-src/master/utils'
JF_BIN_DIR = '/jf-bin'


JF_BUILT_IN_MODELS_PATH = "/jf-bin/built_in_models"
JF_BUILT_IN_DATASETS_PATH = "/jf-bin/built_in_datasets.tar.gz"
JF_BUILT_IN_MODELS_HOST_PATH = "/jfbcore/jf-bin/built_in_models"

JF_BUILT_IN_MODELS_MODEL_HOST_PATH = JF_BUILT_IN_MODELS_HOST_PATH + "/" + "{built_in_model_path}"
JF_BUILT_IN_MODELS_MODEL_POD_PATH = "/built_in_model/"

JF_ROOT_CHECKPOINT_PATH = "/jf-data/ckpt_data" # independent from workspace
JF_ROOT_CHECKPOINT_HOST_PATH = "/jfbcore/jf-data/ckpt_data" # independent from workspace
JF_SUPPORT_BINARY_HOST_PATH = "/jfbcore/jf-bin/support" # Basic support binary 
JF_SUPPORT_BINARY_POD_PATH = "/usr/bin/support"

JF_ADDLIB_HOST_PATH = "/jfbcore/jf-bin/deployment_log"
JF_ADDLIB_POD_PATH = "/addlib"

JF_HPS_RUN_FILE_HOST_PATH = "/jfbcore/jf-bin/hps/" # HPS 실행 파일 위치
JF_HPS_RUN_FILE_POD_PATH = "/hps_runfile" # HPS 실행 파일 위치

JF_ETC_HOST_WORKSPACE_DIR_PATH = JF_ETC_DIR_HOST_PATH + "/{workspace_name}"
JF_ETC_HOST_TRAINING_DIR_PATH = JF_ETC_DIR_HOST_PATH + "/{workspace_name}/{training_name}"

JF_WORKSPACE_PATH = JF_WS_DIR + "/{workspace_name}"

JF_TRAINING_PATH = "/jf-data/workspaces/{workspace_name}/trainings/{training_name}"
JF_TRAINING_HOST_PATH = "/jfbcore/jf-data/workspaces/{workspace_name}/trainings/{training_name}"
JF_TRAINING_POD_PATH = "/jf-training-home"

JF_TRAINING_SRC_PATH = "/jf-data/workspaces/{workspace_name}/trainings/{training_name}/src"
JF_TRAINING_SRC_HOST_PATH = "/jfbcore/jf-data/workspaces/{workspace_name}/trainings/{training_name}/src"
JF_TRAINING_SRC_POD_PATH = "{JF_TRAINING_POD_PATH}/src".format(JF_TRAINING_POD_PATH=JF_TRAINING_POD_PATH)

# JOB Checkpoint 저장 기본 경로
JF_TRAINING_JOB_CHECKPOINT_BASE_DIR_NAME = "job-checkpoints"
JF_TRAINING_JOB_CHECKPOINT_BASE_PATH = "{JF_TRAINING_PATH}/{JF_TRAINING_JOB_CHECKPOINT_BASE_DIR_NAME}".format(JF_TRAINING_PATH=JF_TRAINING_PATH, JF_TRAINING_JOB_CHECKPOINT_BASE_DIR_NAME=JF_TRAINING_JOB_CHECKPOINT_BASE_DIR_NAME)
JF_TRAINING_JOB_CHECKPOINT_BASE_HOST_PATH = "{JF_TRAINING_HOST_PATH}/{JF_TRAINING_JOB_CHECKPOINT_BASE_DIR_NAME}".format(JF_TRAINING_HOST_PATH=JF_TRAINING_HOST_PATH, JF_TRAINING_JOB_CHECKPOINT_BASE_DIR_NAME=JF_TRAINING_JOB_CHECKPOINT_BASE_DIR_NAME)
JF_TRAINING_JOB_CHECKPOINT_BASE_POD_PATH = JF_TRAINING_POD_PATH + "/" + JF_TRAINING_JOB_CHECKPOINT_BASE_DIR_NAME

# JOB Checkpoint Job 별 저장 경로
JF_TRAINING_JOB_CHECKPOINT_ITEM_PATH = JF_TRAINING_JOB_CHECKPOINT_BASE_PATH + "/{job_name}/{job_group_index}" # workspace_name, training_name, job_name, job_group_index
JF_TRAINING_JOB_CHECKPOINT_ITEM_HOST_PATH = JF_TRAINING_JOB_CHECKPOINT_BASE_HOST_PATH + "/{job_name}/{job_group_index}" # workspace_name, training_name, job_name, job_group_index
JF_TRAINING_JOB_CHECKPOINT_ITEM_POD_PATH = JF_TRAINING_JOB_CHECKPOINT_BASE_POD_PATH + "/{job_name}/{job_group_index}" # job_name, job_group_index

JF_TRAINING_CHECKPOINT_ITEM_POD_STATIC_PATH = "/checkpoints"

JF_TRAINING_JOB_LOG_DIR_NAME = "job_logs"
JF_TRAINING_JOB_LOG_DIR_POD_PATH="/{JF_TRAINING_JOB_LOG_DIR_NAME}".format(JF_TRAINING_JOB_LOG_DIR_NAME=JF_TRAINING_JOB_LOG_DIR_NAME)
JF_TRAINING_JOB_LOG_DIR_PATH="{JF_TRAINING_PATH}/{JF_TRAINING_JOB_LOG_DIR_NAME}".format(JF_TRAINING_PATH=JF_TRAINING_PATH, JF_TRAINING_JOB_LOG_DIR_NAME=JF_TRAINING_JOB_LOG_DIR_NAME)
JF_TRAINING_JOB_LOG_DIR_HOST_PATH="{JF_TRAINING_HOST_PATH}/{JF_TRAINING_JOB_LOG_DIR_NAME}".format(JF_TRAINING_HOST_PATH=JF_TRAINING_HOST_PATH, JF_TRAINING_JOB_LOG_DIR_NAME=JF_TRAINING_JOB_LOG_DIR_NAME)

# HPS 저장 경로 관련
JF_TRAINING_HPS_LOG_DIR_NAME = "hps_logs"
JF_TRAINING_HPS_LOG_DIR_POD_PATH = "/{JF_TRAINING_HPS_LOG_DIR_NAME}".format(JF_TRAINING_HPS_LOG_DIR_NAME=JF_TRAINING_HPS_LOG_DIR_NAME)
JF_TRAINING_HPS_LOG_DIR_HOST_PATH = "{JF_TRAINING_HOST_PATH}/{JF_TRAINING_HPS_LOG_DIR_NAME}".format(JF_TRAINING_HOST_PATH=JF_TRAINING_HOST_PATH, JF_TRAINING_HPS_LOG_DIR_NAME=JF_TRAINING_HPS_LOG_DIR_NAME)
JF_TRAINING_HPS_LOG_ORIGINAL_RECORD_FILE_POD_PATH = JF_TRAINING_HPS_LOG_DIR_POD_PATH + "/" + "{hps_id}.json" # JF_TRAINING_POD_PATH + "/" + JF_TRAINING_HPS_LOG_DIR_NAME + "/" + "{hps_id}.json"
JF_TRAINING_HPS_LOG_N_ITER_FILE_DIR_POD_PATH = JF_TRAINING_HPS_LOG_DIR_POD_PATH + "/" + "{hps_id}" # JF_TRAINING_POD_PATH + "/" + JF_TRAINING_HPS_LOG_DIR_NAME + "/" + "{hps_id}"

JF_TRAINING_HPS_CHECKPOINT_ITEM_POD_STATIC_PATH = "/checkpoints-base"
JF_TRAINING_HPS_CHECKPOINT_BASE_DIR_NAME = "hps-checkpoints"
JF_TRAINING_HPS_CHECKPOINT_BASE_PATH = "{JF_TRAINING_PATH}/{JF_TRAINING_HPS_CHECKPOINT_BASE_DIR_NAME}".format(JF_TRAINING_PATH=JF_TRAINING_PATH, JF_TRAINING_HPS_CHECKPOINT_BASE_DIR_NAME=JF_TRAINING_HPS_CHECKPOINT_BASE_DIR_NAME)
JF_TRAINING_HPS_CHECKPOINT_BASE_HOST_PATH = "{JF_TRAINING_HOST_PATH}/{JF_TRAINING_HPS_CHECKPOINT_BASE_DIR_NAME}".format(JF_TRAINING_HOST_PATH=JF_TRAINING_HOST_PATH, JF_TRAINING_HPS_CHECKPOINT_BASE_DIR_NAME=JF_TRAINING_HPS_CHECKPOINT_BASE_DIR_NAME)
JF_TRAINING_HPS_CHECKPOINT_BASE_POD_PATH = JF_TRAINING_POD_PATH + "/" + JF_TRAINING_HPS_CHECKPOINT_BASE_DIR_NAME

JF_TRAINING_HPS_CHECKPOINT_ITEM_PATH = JF_TRAINING_HPS_CHECKPOINT_BASE_PATH + "/{hps_name}/{hps_group_index}"
JF_TRAINING_HPS_CHECKPOINT_ITEM_DIR_PATH = JF_TRAINING_HPS_CHECKPOINT_BASE_PATH + "/{hps_name}/{hps_group_index}/{hps_number}"
JF_TRAINING_HPS_CHECKPOINT_ITEM_HOST_PATH = JF_TRAINING_HPS_CHECKPOINT_BASE_HOST_PATH + "/{hps_name}/{hps_group_index}"
JF_TRAINING_HPS_CHECKPOINT_ITEM_POD_PATH = JF_TRAINING_HPS_CHECKPOINT_BASE_POD_PATH + "/{hps_name}/{hps_group_index}"
JF_TRAINING_HPS_CHECKPOINT_ITEM_POD_DIR_PATH = JF_TRAINING_HPS_CHECKPOINT_BASE_POD_PATH + "/{hps_name}/{hps_group_index}/{hps_number}"

JF_TRAINING_HPS_SAVE_LOAD_FILE_DIR_NAME = "hps_save_load_files"
JF_TRAINING_HPS_SAVE_FILE_DIR_POD_STATIC_PATH = "/{JF_TRAINING_HPS_SAVE_LOAD_FILE_DIR_NAME}".format(JF_TRAINING_HPS_SAVE_LOAD_FILE_DIR_NAME=JF_TRAINING_HPS_SAVE_LOAD_FILE_DIR_NAME)
JF_TRAINING_HPS_SAVE_FILE_DIR_POD_PATH = JF_TRAINING_POD_PATH + "/" + JF_TRAINING_HPS_SAVE_LOAD_FILE_DIR_NAME + "/" + "{hps_name}"
JF_TRAINING_HPS_SAVE_FILE_DIR_HOST_PATH = JF_TRAINING_HOST_PATH + "/" + JF_TRAINING_HPS_SAVE_LOAD_FILE_DIR_NAME + "/" + "{hps_name}"


JF_CHECKPOINT_PATH = "/jf-data/workspaces/{workspace_name}/ckpt_data"
JF_CHECKPOINT_HOST_PATH = "/jfbcore/jf-data/workspaces/{workspace_name}/ckpt_data" # /jfbcore/jf-data/ckpt_data/[CHECKPOINT_ID]/DATA
JF_CHECKPOINT_POD_PATH = "/jf-checkpoint-home"

JF_CHECKPOINT_ITEM_HOST_PATH = JF_CHECKPOINT_HOST_PATH + "/" + "{dir_name}"
JF_CHECKPOINT_ITEM_POD_PATH = JF_CHECKPOINT_POD_PATH + "/" + "{dir_name}"

JF_DEPLOYMENT_DEFAULLT_CUSTOM_API_PATH = JF_BUILT_IN_MODELS_PATH+ '/' +'jf_auto_gen_api_example.py'

JF_DEPLOYMENT_PATH = "/jf-data/workspaces/{workspace_name}/deployments/{deployment_name}"
JF_DEPLOYMENT_HOST_PATH = "/jfbcore/jf-data/workspaces/{workspace_name}/deployments/{deployment_name}"
JF_DEPLOYMENT_POD_PATH = "/jf-deployment-home"

JF_DEPLOYMENT_LOG_DIR_PATH = JF_DEPLOYMENT_PATH + "/log/"
JF_DEPLOYMENT_LOG_DIR_HOST_PATH = JF_DEPLOYMENT_HOST_PATH + "/log/"
JF_DEPLOYMENT_WORKER_LOG_DIR_PATH = JF_DEPLOYMENT_PATH + "/log/{deployment_worker_id}"
JF_DEPLOYMENT_WORKER_LOG_DIR_HOST_PATH = JF_DEPLOYMENT_HOST_PATH + "/log/{deployment_worker_id}"

JF_DATASET_PATH = JF_WS_DIR+"/{workspace_name}/datasets/{access}/{dataset_name}"
JF_DATASET_HOST_DIR = JF_WS_HOST_DIR + "/{workspace_name}/datasets/{access}/{dataset_name}"

JF_DATASET_ITEM_NAME_PATH_IN_POD = "/{dataset_name}"
JF_DATASET_ITEM_BASIC_PATH_IN_POD = "/user_dataset"

JF_STORAGE_FILE_NAME = "{workspace_name}.img"
JF_STORAGE_MOUNTPOINT_PATH = "/jf-storage/{device_name}/"
JF_STORAGE_IMAGE_PATH  = JF_STORAGE_MOUNTPOINT_PATH + JF_STORAGE_FILE_NAME
JF_STORAGE_SHELL_SCRIPT_PATH = "/jfbcore/jf-src/master/{shell_script_name}"

JF_STORAGE_MOUNT_FSTAB_HOST_PATH = "/etc/jfb/fstab_jfb"
JF_STORAGE_WORKSPACE_FSTAB_HOST_PATH = "/etc/jfb/fstab_jfb_ws"
JF_STORAGE_MOUNT_FSTAB_CONTAINER_PATH = "/host_etc_info/jfb/fstab_jfb"
JF_STORAGE_WORKSPACE_FSTAB_CONTAINER_PATH = "/host_etc_info/jfb/fstab_jfb_ws"

POD_STATUS_IN_HOST = "/jfbcore/jf-data/pod-status/{pod_name}"
POD_STATUS_IN_JF_API = "/jf-data/pod-status/{pod_name}"
POD_STATUS_IN_POD = "/pod-status"

POD_STATUS_INSTALLING_FLAG = ".installing"
POD_STATUS_ERROR_FLAG = ".error"
POD_DEVICE_INFO_FLAG = "device_info"
POD_STATUS_STOP_FLAG = ".stop"
POD_STATUS_RUNNING_FLAG = ".running"

POD_STATUS_INSTALLING_FLAG_IN_POD = "{POD_STATUS_IN_POD}/{POD_STATUS_INSTALLING_FLAG}".format(POD_STATUS_IN_POD=POD_STATUS_IN_POD, POD_STATUS_INSTALLING_FLAG=POD_STATUS_INSTALLING_FLAG)
POD_STATUS_ERROR_FLAG_IN_POD = "{POD_STATUS_IN_POD}/{POD_STATUS_ERROR_FLAG}".format(POD_STATUS_IN_POD=POD_STATUS_IN_POD, POD_STATUS_ERROR_FLAG=POD_STATUS_ERROR_FLAG)
POD_DEVICE_INFO_FLAG_IN_POD = "{POD_STATUS_IN_POD}/{POD_DEVICE_INFO_FLAG}".format(POD_STATUS_IN_POD=POD_STATUS_IN_POD, POD_DEVICE_INFO_FLAG=POD_DEVICE_INFO_FLAG)
POD_STATUS_STOP_FLAG_IN_POD = "{POD_STATUS_IN_POD}/{POD_STATUS_STOP_FLAG}".format(POD_STATUS_IN_POD=POD_STATUS_IN_POD, POD_STATUS_STOP_FLAG=POD_STATUS_STOP_FLAG)
POD_STATUS_RUNNING_FLAG_IN_POD = "{POD_STATUS_IN_POD}/{POD_STATUS_RUNNING_FLAG}".format(POD_STATUS_IN_POD=POD_STATUS_IN_POD, POD_STATUS_RUNNING_FLAG=POD_STATUS_RUNNING_FLAG)

# BINARY FILE PATH

TREE_BINARY_PATH = "/jfbcore/jf-bin/support/tree"


# LOG FILE PARAM

POD_RESOURCE_BASE_PATH_IN_POD="/resource_log"
POD_RESOURCE_BASE_PATH_IN_JF_API="/jf-data/pod_resource_usage/{pod_name}"
POD_RESOURCE_BASE_PATH_IN_HOST="/jfbcore/jf-data/pod_resource_usage/{pod_name}"

POD_CPU_RAM_RESOURCE_USAGE_RECORD_FILE_NAME="resource_usage.json"
POD_CPU_RAM_RESOURCE_USAGE_RECORD_FILE_PATH_IN_POD="{POD_RESOURCE_BASE_PATH_IN_POD}/{POD_CPU_RAM_RESOURCE_USAGE_RECORD_FILE_NAME}".format(POD_RESOURCE_BASE_PATH_IN_POD=POD_RESOURCE_BASE_PATH_IN_POD,
                                                                                                                                        POD_CPU_RAM_RESOURCE_USAGE_RECORD_FILE_NAME=POD_CPU_RAM_RESOURCE_USAGE_RECORD_FILE_NAME)
POD_CPU_RAM_RESOURCE_USAGE_RECORD_FILE_PATH_IN_JF_API="{POD_RESOURCE_BASE_PATH_IN_JF_API}/{POD_CPU_RAM_RESOURCE_USAGE_RECORD_FILE_NAME}".format(POD_RESOURCE_BASE_PATH_IN_JF_API=POD_RESOURCE_BASE_PATH_IN_JF_API, 
                                                                                                                                POD_CPU_RAM_RESOURCE_USAGE_RECORD_FILE_NAME=POD_CPU_RAM_RESOURCE_USAGE_RECORD_FILE_NAME)

POD_CPU_RAM_RESOURCE_USAGE_HISTORY_FILE_NAME="resource_usage_history.log"
POD_CPU_RAM_RESOURCE_USAGE_HISTORY_FILE_PATH_IN_POD="{POD_RESOURCE_BASE_PATH_IN_POD}/{POD_CPU_RAM_RESOURCE_USAGE_HISTORY_FILE_NAME}".format(POD_RESOURCE_BASE_PATH_IN_POD=POD_RESOURCE_BASE_PATH_IN_POD,
                                                                                                                                        POD_CPU_RAM_RESOURCE_USAGE_HISTORY_FILE_NAME=POD_CPU_RAM_RESOURCE_USAGE_HISTORY_FILE_NAME)

POD_CPU_RAM_RESOURCE_USAGE_HISTORY_FILE_PATH_IN_JF_API="{POD_RESOURCE_BASE_PATH_IN_JF_API}/{POD_CPU_RAM_RESOURCE_USAGE_HISTORY_FILE_NAME}".format(POD_RESOURCE_BASE_PATH_IN_JF_API=POD_RESOURCE_BASE_PATH_IN_JF_API, 
                                                                                        POD_CPU_RAM_RESOURCE_USAGE_HISTORY_FILE_NAME=POD_CPU_RAM_RESOURCE_USAGE_HISTORY_FILE_NAME)
POD_GPU_USAGE_RECORD_FILE_NAME="gpu_usage.json"
POD_GPU_USAGE_RECORD_FILE_PATH_IN_POD="{POD_RESOURCE_BASE_PATH_IN_POD}/{POD_GPU_USAGE_RECORD_FILE_NAME}".format(POD_RESOURCE_BASE_PATH_IN_POD=POD_RESOURCE_BASE_PATH_IN_POD,
                                                                                                                POD_GPU_USAGE_RECORD_FILE_NAME=POD_GPU_USAGE_RECORD_FILE_NAME)
POD_GPU_USAGE_RECORD_FILE_PATH_IN_JF_API="{POD_RESOURCE_BASE_PATH_IN_JF_API}/{POD_GPU_USAGE_RECORD_FILE_NAME}".format(POD_RESOURCE_BASE_PATH_IN_JF_API=POD_RESOURCE_BASE_PATH_IN_JF_API,
                                                                                                                POD_GPU_USAGE_RECORD_FILE_NAME=POD_GPU_USAGE_RECORD_FILE_NAME)
POD_GPU_USAGE_HISTORY_FILE_NAME="gpu_usage_history.log"
POD_GPU_USAGE_HISTORY_FILE_PATH_IN_POD="{POD_RESOURCE_BASE_PATH_IN_POD}/{POD_GPU_USAGE_HISTORY_FILE_NAME}".format(POD_RESOURCE_BASE_PATH_IN_POD=POD_RESOURCE_BASE_PATH_IN_POD,
                                                                                                                POD_GPU_USAGE_HISTORY_FILE_NAME=POD_GPU_USAGE_HISTORY_FILE_NAME)
POD_GPU_USAGE_HISTORY_FILE_PATH_IN_JF_API="{POD_RESOURCE_BASE_PATH_IN_JF_API}/{POD_GPU_USAGE_HISTORY_FILE_NAME}".format(POD_RESOURCE_BASE_PATH_IN_JF_API=POD_RESOURCE_BASE_PATH_IN_JF_API,
                                                                                                                POD_GPU_USAGE_HISTORY_FILE_NAME=POD_GPU_USAGE_HISTORY_FILE_NAME)

POD_NETWORK_USAGE_RECORD_FILE_NAME="network_usage.json"
POD_NETWORK_USAGE_RECORD_FILE_PATH_IN_POD="{POD_RESOURCE_BASE_PATH_IN_POD}/{POD_NETWORK_USAGE_RECORD_FILE_NAME}".format(POD_RESOURCE_BASE_PATH_IN_POD=POD_RESOURCE_BASE_PATH_IN_POD,
                                                                                                                POD_NETWORK_USAGE_RECORD_FILE_NAME=POD_NETWORK_USAGE_RECORD_FILE_NAME)
POD_NETWORK_USAGE_RECORD_FILE_PATH_IN_JF_API="{POD_RESOURCE_BASE_PATH_IN_JF_API}/{POD_NETWORK_USAGE_RECORD_FILE_NAME}".format(POD_RESOURCE_BASE_PATH_IN_JF_API=POD_RESOURCE_BASE_PATH_IN_JF_API,
                                                                                                                POD_NETWORK_USAGE_RECORD_FILE_NAME=POD_NETWORK_USAGE_RECORD_FILE_NAME)

POD_NETWORK_USAGE_HISTORY_FILE_NAME="network_usage_history.log"
POD_NETWORK_USAGE_HISTORY_FILE_PATH_IN_POD="{POD_RESOURCE_BASE_PATH_IN_POD}/{POD_NETWORK_USAGE_HISTORY_FILE_NAME}".format(POD_RESOURCE_BASE_PATH_IN_POD=POD_RESOURCE_BASE_PATH_IN_POD,
                                                                                                                POD_NETWORK_USAGE_HISTORY_FILE_NAME=POD_NETWORK_USAGE_HISTORY_FILE_NAME)
POD_NETWORK_USAGE_HISTORY_FILE_PATH_IN_JF_API="{POD_RESOURCE_BASE_PATH_IN_JF_API}/{POD_NETWORK_USAGE_HISTORY_FILE_NAME}".format(POD_RESOURCE_BASE_PATH_IN_JF_API=POD_RESOURCE_BASE_PATH_IN_JF_API,
                                                                                                                POD_NETWORK_USAGE_HISTORY_FILE_NAME=POD_NETWORK_USAGE_HISTORY_FILE_NAME)


########## DEPLOYMENT ONLY ###############
POD_API_LOG_BASE_PATH_IN_POD="/log"
POD_API_LOG_BASE_PATH_IN_JF_API="{DEPLOYMENT_HOME_IN_JF_API}/log/{DEPLOYMENT_WORKER_ID}"
POD_API_LOG_BASE_PATH_IN_HOST_PATH="{DEPLOYMENT_HOME_IN_HOST}/log/{DEPLOYMENT_WORKER_ID}"

POD_API_LOG_FILE_NAME="monitor.txt"
POD_API_LOG_FILE_PATH_IN_POD="{POD_API_LOG_BASE_PATH_IN_POD}/{POD_API_LOG_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_POD=POD_API_LOG_BASE_PATH_IN_POD, POD_API_LOG_FILE_NAME=POD_API_LOG_FILE_NAME)
POD_API_LOG_FILE_PATH_IN_JF_API="{POD_API_LOG_BASE_PATH_IN_JF_API}/{POD_API_LOG_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_JF_API=POD_API_LOG_BASE_PATH_IN_JF_API, POD_API_LOG_FILE_NAME=POD_API_LOG_FILE_NAME)

POD_API_LOG_IMPORT_CHECK_FILE_NAME="import.txt"
POD_API_LOG_IMPORT_CHECK_FILE_PATH_IN_POD="{POD_API_LOG_BASE_PATH_IN_POD}/{POD_API_LOG_IMPORT_CHECK_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_POD=POD_API_LOG_BASE_PATH_IN_POD, POD_API_LOG_IMPORT_CHECK_FILE_NAME=POD_API_LOG_IMPORT_CHECK_FILE_NAME)
POD_API_LOG_IMPORT_CHECK_FILE_PATH_IN_JF_API="{POD_API_LOG_BASE_PATH_IN_JF_API}/{POD_API_LOG_IMPORT_CHECK_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_JF_API=POD_API_LOG_BASE_PATH_IN_JF_API, POD_API_LOG_IMPORT_CHECK_FILE_NAME=POD_API_LOG_IMPORT_CHECK_FILE_NAME)

POD_NGINX_ACCESS_LOG_FILE_NAME="nginx_access.log"
POD_NGINX_ACEESS_LOG_FILE_PATH_IN_POD="{POD_API_LOG_BASE_PATH_IN_POD}/{POD_NGINX_ACCESS_LOG_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_POD=POD_API_LOG_BASE_PATH_IN_POD, POD_NGINX_ACCESS_LOG_FILE_NAME=POD_NGINX_ACCESS_LOG_FILE_NAME)
POD_NGINX_ACEESS_LOG_FILE_PATH_IN_JF_API="{POD_API_LOG_BASE_PATH_IN_JF_API}/{POD_NGINX_ACCESS_LOG_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_JF_API=POD_API_LOG_BASE_PATH_IN_JF_API, POD_NGINX_ACCESS_LOG_FILE_NAME=POD_NGINX_ACCESS_LOG_FILE_NAME)
def GET_POD_NGINX_ACEESS_LOG_FILE_PATH_IN_JF_API(workspace_name, deployment_name, deployment_worker_id):
    DEPLOYMENT_HOME_IN_JF_API = JF_DEPLOYMENT_PATH.format(workspace_name=workspace_name, deployment_name=deployment_name)
    return POD_NGINX_ACEESS_LOG_FILE_PATH_IN_JF_API.format(DEPLOYMENT_HOME_IN_JF_API=DEPLOYMENT_HOME_IN_JF_API, DEPLOYMENT_WORKER_ID=deployment_worker_id)


POD_NGINX_ERROR_LOG_FILE_NAME="nginx_error.log"
POD_NGINX_ERROR_LOG_FILE_PATH_IN_POD="{POD_API_LOG_BASE_PATH_IN_POD}/{POD_NGINX_ERROR_LOG_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_POD=POD_API_LOG_BASE_PATH_IN_POD, POD_NGINX_ERROR_LOG_FILE_NAME=POD_NGINX_ERROR_LOG_FILE_NAME)

POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_NAME="nginx_access_per_hour.log"
POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_PATH_IN_POD="{POD_API_LOG_BASE_PATH_IN_POD}/{POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_POD=POD_API_LOG_BASE_PATH_IN_POD, POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_NAME=POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_NAME)
POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_PATH_IN_JF_API="{POD_API_LOG_BASE_PATH_IN_JF_API}/{POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_JF_API=POD_API_LOG_BASE_PATH_IN_JF_API, POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_NAME=POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_NAME)
def GET_POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_PATH_IN_JF_API(workspace_name, deployment_name, deployment_worker_id):
    DEPLOYMENT_HOME_IN_JF_API = JF_DEPLOYMENT_PATH.format(workspace_name=workspace_name, deployment_name=deployment_name)
    return POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_PATH_IN_JF_API.format(DEPLOYMENT_HOME_IN_JF_API=DEPLOYMENT_HOME_IN_JF_API, DEPLOYMENT_WORKER_ID=deployment_worker_id)

POD_API_LOG_COUNT_FILE_NAME="count.json"

POD_NGINX_LOG_COUNT_FILE_NAME="nginx_count.json"
POD_NGINX_LOG_COUNT_FILE_PATH_IN_POD="{POD_API_LOG_BASE_PATH_IN_POD}/{POD_NGINX_LOG_COUNT_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_POD=POD_API_LOG_BASE_PATH_IN_POD, POD_NGINX_LOG_COUNT_FILE_NAME=POD_NGINX_LOG_COUNT_FILE_NAME)
POD_NGINX_LOG_COUNT_FILE_PATH_IN_JF_API="{POD_API_LOG_BASE_PATH_IN_JF_API}/{POD_NGINX_LOG_COUNT_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_JF_API=POD_API_LOG_BASE_PATH_IN_JF_API, POD_NGINX_LOG_COUNT_FILE_NAME=POD_NGINX_LOG_COUNT_FILE_NAME)
def GET_POD_NGINX_LOG_COUNT_FILE_PATH_IN_JF_API(workspace_name, deployment_name, deployment_worker_id):
    DEPLOYMENT_HOME_IN_JF_API = JF_DEPLOYMENT_PATH.format(workspace_name=workspace_name, deployment_name=deployment_name)
    return POD_NGINX_LOG_COUNT_FILE_PATH_IN_JF_API.format(DEPLOYMENT_HOME_IN_JF_API=DEPLOYMENT_HOME_IN_JF_API, DEPLOYMENT_WORKER_ID=deployment_worker_id)


POD_RUN_TIME_FILE_NAME="pod_run_time.json"
POD_RUN_TIME_FILE_PATH_IN_POD="{POD_API_LOG_BASE_PATH_IN_POD}/{POD_RUN_TIME_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_POD=POD_API_LOG_BASE_PATH_IN_POD, POD_RUN_TIME_FILE_NAME=POD_RUN_TIME_FILE_NAME)
POD_RUN_TIME_FILE_PATH_IN_JF_API="{POD_API_LOG_BASE_PATH_IN_JF_API}/{POD_RUN_TIME_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_JF_API=POD_API_LOG_BASE_PATH_IN_JF_API, POD_RUN_TIME_FILE_NAME=POD_RUN_TIME_FILE_NAME)
def GET_POD_RUN_TIME_FILE_PATH_IN_JF_API(workspace_name, deployment_name, deployment_worker_id):
    DEPLOYMENT_HOME_IN_JF_API = JF_DEPLOYMENT_PATH.format(workspace_name=workspace_name, deployment_name=deployment_name)
    return POD_RUN_TIME_FILE_PATH_IN_JF_API.format(DEPLOYMENT_HOME_IN_JF_API=DEPLOYMENT_HOME_IN_JF_API, DEPLOYMENT_WORKER_ID=deployment_worker_id)

POD_DASHBOARD_HISTORY_FILE_NAME="dashboard_history.json"
POD_DASHBOARD_HISTORY_BACK_FILE_NAME="dashboard_history_bak.json"
POD_DASHBOARD_LIVE_HISTORY_FILE_NAME="dashboard_live_history.json"
POD_DASHBOARD_LIVE_HISTORY_BACK_FILE_NAME="dashboard_live_history_bak.json"


#FILEBROWSER
FILEBROWSER_DB_PATH = "$JF_HOME/src/.filebrowser/"
FILEBROWSER_PASSWORD_CHANGE_SCRIPT_PATH = "/"
FILEBROWSER_PASSWORD_CHANGE_LOG_FILE_NAME = "password_change.log"
FIELBROWSER_PASSWORD_CHANGE_SCRIPT_FILE_NAME = "filebrowser_admin_pw_change.sh"
FILEBROWSER_PASSWORD_CHANGE_FAILED_LOG_PATH = "/password_change_faile.log"
# FILEBROWSER_BINARY_PATH = "/"